version: '3'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - hma-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - hma-network

  # Backend service (API from the demo)
  backend:
    build:
      context: ../demo/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../demo/api:/app
      - backend-data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - hma-network

  # You can uncomment the redis-commander section if you want a web UI to manage Redis
  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379
  #     - HTTP_USER=admin
  #     - HTTP_PASSWORD=admin
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - redis
  #   networks:
  #     - hma-network

volumes:
  redis-data:
  backend-data:

networks:
  hma-network:
    driver: bridge 