name: ThreatExchange Library CI - Ruby
on:
  push:
    branches:
    - master
    paths:
    - 'ruby/**'
  pull_request:
    branches:
    - master
    paths:
    - 'ruby/**'

defaults:
  run:
    working-directory: ruby

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
